// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: Replication/protobuf/communication.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewNodeRequest_Type int32

const (
	NewNodeRequest_Server   NewNodeRequest_Type = 0
	NewNodeRequest_FrontEnd NewNodeRequest_Type = 1
)

// Enum value maps for NewNodeRequest_Type.
var (
	NewNodeRequest_Type_name = map[int32]string{
		0: "Server",
		1: "FrontEnd",
	}
	NewNodeRequest_Type_value = map[string]int32{
		"Server":   0,
		"FrontEnd": 1,
	}
)

func (x NewNodeRequest_Type) Enum() *NewNodeRequest_Type {
	p := new(NewNodeRequest_Type)
	*p = x
	return p
}

func (x NewNodeRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewNodeRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_Replication_protobuf_communication_proto_enumTypes[0].Descriptor()
}

func (NewNodeRequest_Type) Type() protoreflect.EnumType {
	return &file_Replication_protobuf_communication_proto_enumTypes[0]
}

func (x NewNodeRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NewNodeRequest_Type.Descriptor instead.
func (NewNodeRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_Replication_protobuf_communication_proto_rawDescGZIP(), []int{0, 0}
}

// The request message containing the Node's name.
type NewNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type NewNodeRequest_Type `protobuf:"varint,2,opt,name=type,proto3,enum=communication.NewNodeRequest_Type" json:"type,omitempty"`
}

func (x *NewNodeRequest) Reset() {
	*x = NewNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replication_protobuf_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNodeRequest) ProtoMessage() {}

func (x *NewNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_protobuf_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNodeRequest.ProtoReflect.Descriptor instead.
func (*NewNodeRequest) Descriptor() ([]byte, []int) {
	return file_Replication_protobuf_communication_proto_rawDescGZIP(), []int{0}
}

func (x *NewNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewNodeRequest) GetType() NewNodeRequest_Type {
	if x != nil {
		return x.Type
	}
	return NewNodeRequest_Server
}

// The response message containing if the addition was succesful
type NewNodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewNodeReply) Reset() {
	*x = NewNodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replication_protobuf_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNodeReply) ProtoMessage() {}

func (x *NewNodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_protobuf_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNodeReply.ProtoReflect.Descriptor instead.
func (*NewNodeReply) Descriptor() ([]byte, []int) {
	return file_Replication_protobuf_communication_proto_rawDescGZIP(), []int{1}
}

type ServerChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewServers       []string `protobuf:"bytes,1,rep,name=newServers,proto3" json:"newServers,omitempty"`
	NewFrontEnds     []string `protobuf:"bytes,2,rep,name=newFrontEnds,proto3" json:"newFrontEnds,omitempty"`
	NewCurrentWinner string   `protobuf:"bytes,3,opt,name=newCurrentWinner,proto3" json:"newCurrentWinner,omitempty"`
	NewHighestBid    int32    `protobuf:"varint,4,opt,name=newHighestBid,proto3" json:"newHighestBid,omitempty"`
	NewPrimaryServer string   `protobuf:"bytes,5,opt,name=newPrimaryServer,proto3" json:"newPrimaryServer,omitempty"`
}

func (x *ServerChangeRequest) Reset() {
	*x = ServerChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replication_protobuf_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChangeRequest) ProtoMessage() {}

func (x *ServerChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_protobuf_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChangeRequest.ProtoReflect.Descriptor instead.
func (*ServerChangeRequest) Descriptor() ([]byte, []int) {
	return file_Replication_protobuf_communication_proto_rawDescGZIP(), []int{2}
}

func (x *ServerChangeRequest) GetNewServers() []string {
	if x != nil {
		return x.NewServers
	}
	return nil
}

func (x *ServerChangeRequest) GetNewFrontEnds() []string {
	if x != nil {
		return x.NewFrontEnds
	}
	return nil
}

func (x *ServerChangeRequest) GetNewCurrentWinner() string {
	if x != nil {
		return x.NewCurrentWinner
	}
	return ""
}

func (x *ServerChangeRequest) GetNewHighestBid() int32 {
	if x != nil {
		return x.NewHighestBid
	}
	return 0
}

func (x *ServerChangeRequest) GetNewPrimaryServer() string {
	if x != nil {
		return x.NewPrimaryServer
	}
	return ""
}

type ServerChangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerChangeReply) Reset() {
	*x = ServerChangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Replication_protobuf_communication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerChangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChangeReply) ProtoMessage() {}

func (x *ServerChangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_Replication_protobuf_communication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChangeReply.ProtoReflect.Descriptor instead.
func (*ServerChangeReply) Descriptor() ([]byte, []int) {
	return file_Replication_protobuf_communication_proto_rawDescGZIP(), []int{3}
}

var File_Replication_protobuf_communication_proto protoreflect.FileDescriptor

var file_Replication_protobuf_communication_proto_rawDesc = []byte{
	0x0a, 0x28, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7e, 0x0a, 0x0e, 0x4e, 0x65, 0x77,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65,
	0x77, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46,
	0x72, 0x6f, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x65, 0x77,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xd7, 0x01, 0x0a, 0x13, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x45, 0x6e, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x45, 0x6e, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x65, 0x77, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x6e, 0x65, 0x77, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x48, 0x69, 0x67,
	0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x65, 0x77, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6e, 0x65, 0x77, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xbd, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x65, 0x0a, 0x1b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x68, 0x74, 0x74, 0x70,
	0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a,
	0x61, 0x63, 0x6f, 0x62, 0x4d, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x4d, 0x69, 0x6e, 0x69, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x33, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Replication_protobuf_communication_proto_rawDescOnce sync.Once
	file_Replication_protobuf_communication_proto_rawDescData = file_Replication_protobuf_communication_proto_rawDesc
)

func file_Replication_protobuf_communication_proto_rawDescGZIP() []byte {
	file_Replication_protobuf_communication_proto_rawDescOnce.Do(func() {
		file_Replication_protobuf_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_Replication_protobuf_communication_proto_rawDescData)
	})
	return file_Replication_protobuf_communication_proto_rawDescData
}

var file_Replication_protobuf_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Replication_protobuf_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Replication_protobuf_communication_proto_goTypes = []interface{}{
	(NewNodeRequest_Type)(0),    // 0: communication.NewNodeRequest.Type
	(*NewNodeRequest)(nil),      // 1: communication.NewNodeRequest
	(*NewNodeReply)(nil),        // 2: communication.NewNodeReply
	(*ServerChangeRequest)(nil), // 3: communication.ServerChangeRequest
	(*ServerChangeReply)(nil),   // 4: communication.ServerChangeReply
}
var file_Replication_protobuf_communication_proto_depIdxs = []int32{
	0, // 0: communication.NewNodeRequest.type:type_name -> communication.NewNodeRequest.Type
	1, // 1: communication.Replication.NewNode:input_type -> communication.NewNodeRequest
	3, // 2: communication.Replication.ServerInternalCommunication:input_type -> communication.ServerChangeRequest
	2, // 3: communication.Replication.NewNode:output_type -> communication.NewNodeReply
	4, // 4: communication.Replication.ServerInternalCommunication:output_type -> communication.ServerChangeReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Replication_protobuf_communication_proto_init() }
func file_Replication_protobuf_communication_proto_init() {
	if File_Replication_protobuf_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Replication_protobuf_communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Replication_protobuf_communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Replication_protobuf_communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Replication_protobuf_communication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerChangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Replication_protobuf_communication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Replication_protobuf_communication_proto_goTypes,
		DependencyIndexes: file_Replication_protobuf_communication_proto_depIdxs,
		EnumInfos:         file_Replication_protobuf_communication_proto_enumTypes,
		MessageInfos:      file_Replication_protobuf_communication_proto_msgTypes,
	}.Build()
	File_Replication_protobuf_communication_proto = out.File
	file_Replication_protobuf_communication_proto_rawDesc = nil
	file_Replication_protobuf_communication_proto_goTypes = nil
	file_Replication_protobuf_communication_proto_depIdxs = nil
}
